// Generated by CoffeeScript 1.6.2
var http, mu;

http = require('http');

mu = require('mu2');

mu.root = "" + __dirname + "/templates";

mu.compileAndRender('index.html', {
  name: "john"
}).on('data', function(data) {
  return console.log(data.toString());
});

http.createServer(function(request, response) {
  response.writeHead(200, {
    "Content-Type": "text/plain"
  });
  response.write("Hello World!");
  return response.end();
}).listen(8888);
